joint_limits:
  wam/shoulder_pitch_joint:
    has_velocity_limits: true
    #max_velocity: 1.5
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  wam/wrist_pitch_joint:
    has_velocity_limits: true
    #max_velocity: 1.5
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  wam/wrist_yaw_joint:
    has_velocity_limits: true
    #max_velocity: 1.5
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  wam/shoulder_yaw_joint:
    has_velocity_limits: true
    #max_velocity: 1.5
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  wam/palm_yaw_joint:
    has_velocity_limits: true
    #max_velocity: 1.0
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  wam/elbow_pitch_joint:
    has_velocity_limits: true
    #max_velocity: 1.0
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  wam/base_yaw_joint:
    has_velocity_limits: true
    #max_velocity: 1.0
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
