controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [wam/base_yaw_joint, wam/shoulder_pitch_joint, wam/shoulder_yaw_joint, wam/elbow_pitch_joint, wam/wrist_yaw_joint, wam/wrist_pitch_joint, wam/palm_yaw_joint]
