// Generated by gencpp from file wam_msgs/BHandSpreadPos.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_BHANDSPREADPOS_H
#define WAM_MSGS_MESSAGE_BHANDSPREADPOS_H

#include <ros/service_traits.h>


#include <wam_msgs/BHandSpreadPosRequest.h>
#include <wam_msgs/BHandSpreadPosResponse.h>


namespace wam_msgs
{

struct BHandSpreadPos
{

typedef BHandSpreadPosRequest Request;
typedef BHandSpreadPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandSpreadPos
} // namespace wam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_msgs::BHandSpreadPos > {
  static const char* value()
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const ::wam_msgs::BHandSpreadPos&) { return value(); }
};

template<>
struct DataType< ::wam_msgs::BHandSpreadPos > {
  static const char* value()
  {
    return "wam_msgs/BHandSpreadPos";
  }

  static const char* value(const ::wam_msgs::BHandSpreadPos&) { return value(); }
};


// service_traits::MD5Sum< ::wam_msgs::BHandSpreadPosRequest> should match 
// service_traits::MD5Sum< ::wam_msgs::BHandSpreadPos > 
template<>
struct MD5Sum< ::wam_msgs::BHandSpreadPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_msgs::BHandSpreadPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::BHandSpreadPosRequest> should match 
// service_traits::DataType< ::wam_msgs::BHandSpreadPos > 
template<>
struct DataType< ::wam_msgs::BHandSpreadPosRequest>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_msgs::BHandSpreadPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_msgs::BHandSpreadPosResponse> should match 
// service_traits::MD5Sum< ::wam_msgs::BHandSpreadPos > 
template<>
struct MD5Sum< ::wam_msgs::BHandSpreadPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_msgs::BHandSpreadPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::BHandSpreadPosResponse> should match 
// service_traits::DataType< ::wam_msgs::BHandSpreadPos > 
template<>
struct DataType< ::wam_msgs::BHandSpreadPosResponse>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_msgs::BHandSpreadPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_MSGS_MESSAGE_BHANDSPREADPOS_H
