// Generated by gencpp from file wam_msgs/BHandFingerVel.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_BHANDFINGERVEL_H
#define WAM_MSGS_MESSAGE_BHANDFINGERVEL_H

#include <ros/service_traits.h>


#include <wam_msgs/BHandFingerVelRequest.h>
#include <wam_msgs/BHandFingerVelResponse.h>


namespace wam_msgs
{

struct BHandFingerVel
{

typedef BHandFingerVelRequest Request;
typedef BHandFingerVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandFingerVel
} // namespace wam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_msgs::BHandFingerVel > {
  static const char* value()
  {
    return "d4b1534f81253843d8e7435f97fbf189";
  }

  static const char* value(const ::wam_msgs::BHandFingerVel&) { return value(); }
};

template<>
struct DataType< ::wam_msgs::BHandFingerVel > {
  static const char* value()
  {
    return "wam_msgs/BHandFingerVel";
  }

  static const char* value(const ::wam_msgs::BHandFingerVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_msgs::BHandFingerVelRequest> should match 
// service_traits::MD5Sum< ::wam_msgs::BHandFingerVel > 
template<>
struct MD5Sum< ::wam_msgs::BHandFingerVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_msgs::BHandFingerVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::BHandFingerVelRequest> should match 
// service_traits::DataType< ::wam_msgs::BHandFingerVel > 
template<>
struct DataType< ::wam_msgs::BHandFingerVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_msgs::BHandFingerVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_msgs::BHandFingerVelResponse> should match 
// service_traits::MD5Sum< ::wam_msgs::BHandFingerVel > 
template<>
struct MD5Sum< ::wam_msgs::BHandFingerVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_msgs::BHandFingerVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::BHandFingerVelResponse> should match 
// service_traits::DataType< ::wam_msgs::BHandFingerVel > 
template<>
struct DataType< ::wam_msgs::BHandFingerVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_msgs::BHandFingerVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_MSGS_MESSAGE_BHANDFINGERVEL_H
