// Generated by gencpp from file wam_msgs/BHandSpreadVel.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_BHANDSPREADVEL_H
#define WAM_MSGS_MESSAGE_BHANDSPREADVEL_H

#include <ros/service_traits.h>


#include <wam_msgs/BHandSpreadVelRequest.h>
#include <wam_msgs/BHandSpreadVelResponse.h>


namespace wam_msgs
{

struct BHandSpreadVel
{

typedef BHandSpreadVelRequest Request;
typedef BHandSpreadVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandSpreadVel
} // namespace wam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_msgs::BHandSpreadVel > {
  static const char* value()
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const ::wam_msgs::BHandSpreadVel&) { return value(); }
};

template<>
struct DataType< ::wam_msgs::BHandSpreadVel > {
  static const char* value()
  {
    return "wam_msgs/BHandSpreadVel";
  }

  static const char* value(const ::wam_msgs::BHandSpreadVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_msgs::BHandSpreadVelRequest> should match 
// service_traits::MD5Sum< ::wam_msgs::BHandSpreadVel > 
template<>
struct MD5Sum< ::wam_msgs::BHandSpreadVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_msgs::BHandSpreadVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::BHandSpreadVelRequest> should match 
// service_traits::DataType< ::wam_msgs::BHandSpreadVel > 
template<>
struct DataType< ::wam_msgs::BHandSpreadVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_msgs::BHandSpreadVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_msgs::BHandSpreadVelResponse> should match 
// service_traits::MD5Sum< ::wam_msgs::BHandSpreadVel > 
template<>
struct MD5Sum< ::wam_msgs::BHandSpreadVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_msgs::BHandSpreadVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::BHandSpreadVelResponse> should match 
// service_traits::DataType< ::wam_msgs::BHandSpreadVel > 
template<>
struct DataType< ::wam_msgs::BHandSpreadVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_msgs::BHandSpreadVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_MSGS_MESSAGE_BHANDSPREADVEL_H
