// Generated by gencpp from file wam_msgs/GravityComp.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_GRAVITYCOMP_H
#define WAM_MSGS_MESSAGE_GRAVITYCOMP_H

#include <ros/service_traits.h>


#include <wam_msgs/GravityCompRequest.h>
#include <wam_msgs/GravityCompResponse.h>


namespace wam_msgs
{

struct GravityComp
{

typedef GravityCompRequest Request;
typedef GravityCompResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GravityComp
} // namespace wam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_msgs::GravityComp > {
  static const char* value()
  {
    return "f83a9fe078fab9865d863fbf215e1c14";
  }

  static const char* value(const ::wam_msgs::GravityComp&) { return value(); }
};

template<>
struct DataType< ::wam_msgs::GravityComp > {
  static const char* value()
  {
    return "wam_msgs/GravityComp";
  }

  static const char* value(const ::wam_msgs::GravityComp&) { return value(); }
};


// service_traits::MD5Sum< ::wam_msgs::GravityCompRequest> should match 
// service_traits::MD5Sum< ::wam_msgs::GravityComp > 
template<>
struct MD5Sum< ::wam_msgs::GravityCompRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::GravityComp >::value();
  }
  static const char* value(const ::wam_msgs::GravityCompRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::GravityCompRequest> should match 
// service_traits::DataType< ::wam_msgs::GravityComp > 
template<>
struct DataType< ::wam_msgs::GravityCompRequest>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::GravityComp >::value();
  }
  static const char* value(const ::wam_msgs::GravityCompRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_msgs::GravityCompResponse> should match 
// service_traits::MD5Sum< ::wam_msgs::GravityComp > 
template<>
struct MD5Sum< ::wam_msgs::GravityCompResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::GravityComp >::value();
  }
  static const char* value(const ::wam_msgs::GravityCompResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::GravityCompResponse> should match 
// service_traits::DataType< ::wam_msgs::GravityComp > 
template<>
struct DataType< ::wam_msgs::GravityCompResponse>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::GravityComp >::value();
  }
  static const char* value(const ::wam_msgs::GravityCompResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_MSGS_MESSAGE_GRAVITYCOMP_H
