// Generated by gencpp from file wam_msgs/LEDControlRequest.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_LEDCONTROLREQUEST_H
#define WAM_MSGS_MESSAGE_LEDCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace wam_msgs
{
template <class ContainerAllocator>
struct LEDControlRequest_
{
  typedef LEDControlRequest_<ContainerAllocator> Type;

  LEDControlRequest_()
    : turn_on()  {
    }
  LEDControlRequest_(const ContainerAllocator& _alloc)
    : turn_on(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _turn_on_type;
  _turn_on_type turn_on;




  typedef boost::shared_ptr< ::wam_msgs::LEDControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_msgs::LEDControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LEDControlRequest_

typedef ::wam_msgs::LEDControlRequest_<std::allocator<void> > LEDControlRequest;

typedef boost::shared_ptr< ::wam_msgs::LEDControlRequest > LEDControlRequestPtr;
typedef boost::shared_ptr< ::wam_msgs::LEDControlRequest const> LEDControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_msgs::LEDControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_msgs::LEDControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'wam_msgs': ['/home/marcus/catkin_ws_WAM/src/wam_common/wam_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_msgs::LEDControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_msgs::LEDControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_msgs::LEDControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_msgs::LEDControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_msgs::LEDControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_msgs::LEDControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_msgs::LEDControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4cf4d84661c7dde87aee2c1b97ddf9d";
  }

  static const char* value(const ::wam_msgs::LEDControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4cf4d84661c7ddeULL;
  static const uint64_t static_value2 = 0x87aee2c1b97ddf9dULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_msgs::LEDControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_msgs/LEDControlRequest";
  }

  static const char* value(const ::wam_msgs::LEDControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_msgs::LEDControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool turn_on\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
";
  }

  static const char* value(const ::wam_msgs::LEDControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_msgs::LEDControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turn_on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LEDControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_msgs::LEDControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_msgs::LEDControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "turn_on: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.turn_on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_MSGS_MESSAGE_LEDCONTROLREQUEST_H
