// Generated by gencpp from file wam_msgs/LEDControl.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_LEDCONTROL_H
#define WAM_MSGS_MESSAGE_LEDCONTROL_H

#include <ros/service_traits.h>


#include <wam_msgs/LEDControlRequest.h>
#include <wam_msgs/LEDControlResponse.h>


namespace wam_msgs
{

struct LEDControl
{

typedef LEDControlRequest Request;
typedef LEDControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LEDControl
} // namespace wam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_msgs::LEDControl > {
  static const char* value()
  {
    return "e4cf4d84661c7dde87aee2c1b97ddf9d";
  }

  static const char* value(const ::wam_msgs::LEDControl&) { return value(); }
};

template<>
struct DataType< ::wam_msgs::LEDControl > {
  static const char* value()
  {
    return "wam_msgs/LEDControl";
  }

  static const char* value(const ::wam_msgs::LEDControl&) { return value(); }
};


// service_traits::MD5Sum< ::wam_msgs::LEDControlRequest> should match 
// service_traits::MD5Sum< ::wam_msgs::LEDControl > 
template<>
struct MD5Sum< ::wam_msgs::LEDControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::LEDControl >::value();
  }
  static const char* value(const ::wam_msgs::LEDControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::LEDControlRequest> should match 
// service_traits::DataType< ::wam_msgs::LEDControl > 
template<>
struct DataType< ::wam_msgs::LEDControlRequest>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::LEDControl >::value();
  }
  static const char* value(const ::wam_msgs::LEDControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_msgs::LEDControlResponse> should match 
// service_traits::MD5Sum< ::wam_msgs::LEDControl > 
template<>
struct MD5Sum< ::wam_msgs::LEDControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::LEDControl >::value();
  }
  static const char* value(const ::wam_msgs::LEDControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::LEDControlResponse> should match 
// service_traits::DataType< ::wam_msgs::LEDControl > 
template<>
struct DataType< ::wam_msgs::LEDControlResponse>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::LEDControl >::value();
  }
  static const char* value(const ::wam_msgs::LEDControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_MSGS_MESSAGE_LEDCONTROL_H
