// Generated by gencpp from file wam_msgs/BHandFingerPos.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_BHANDFINGERPOS_H
#define WAM_MSGS_MESSAGE_BHANDFINGERPOS_H

#include <ros/service_traits.h>


#include <wam_msgs/BHandFingerPosRequest.h>
#include <wam_msgs/BHandFingerPosResponse.h>


namespace wam_msgs
{

struct BHandFingerPos
{

typedef BHandFingerPosRequest Request;
typedef BHandFingerPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandFingerPos
} // namespace wam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_msgs::BHandFingerPos > {
  static const char* value()
  {
    return "b8c122f38450d0302ba1a30c9c588995";
  }

  static const char* value(const ::wam_msgs::BHandFingerPos&) { return value(); }
};

template<>
struct DataType< ::wam_msgs::BHandFingerPos > {
  static const char* value()
  {
    return "wam_msgs/BHandFingerPos";
  }

  static const char* value(const ::wam_msgs::BHandFingerPos&) { return value(); }
};


// service_traits::MD5Sum< ::wam_msgs::BHandFingerPosRequest> should match 
// service_traits::MD5Sum< ::wam_msgs::BHandFingerPos > 
template<>
struct MD5Sum< ::wam_msgs::BHandFingerPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_msgs::BHandFingerPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::BHandFingerPosRequest> should match 
// service_traits::DataType< ::wam_msgs::BHandFingerPos > 
template<>
struct DataType< ::wam_msgs::BHandFingerPosRequest>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_msgs::BHandFingerPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_msgs::BHandFingerPosResponse> should match 
// service_traits::MD5Sum< ::wam_msgs::BHandFingerPos > 
template<>
struct MD5Sum< ::wam_msgs::BHandFingerPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_msgs::BHandFingerPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::BHandFingerPosResponse> should match 
// service_traits::DataType< ::wam_msgs::BHandFingerPos > 
template<>
struct DataType< ::wam_msgs::BHandFingerPosResponse>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_msgs::BHandFingerPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_MSGS_MESSAGE_BHANDFINGERPOS_H
