// Generated by gencpp from file wam_msgs/JointMove.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_JOINTMOVE_H
#define WAM_MSGS_MESSAGE_JOINTMOVE_H

#include <ros/service_traits.h>


#include <wam_msgs/JointMoveRequest.h>
#include <wam_msgs/JointMoveResponse.h>


namespace wam_msgs
{

struct JointMove
{

typedef JointMoveRequest Request;
typedef JointMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointMove
} // namespace wam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_msgs::JointMove > {
  static const char* value()
  {
    return "e2a0e438b445b98def0f0ba6a2a85f58";
  }

  static const char* value(const ::wam_msgs::JointMove&) { return value(); }
};

template<>
struct DataType< ::wam_msgs::JointMove > {
  static const char* value()
  {
    return "wam_msgs/JointMove";
  }

  static const char* value(const ::wam_msgs::JointMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_msgs::JointMoveRequest> should match 
// service_traits::MD5Sum< ::wam_msgs::JointMove > 
template<>
struct MD5Sum< ::wam_msgs::JointMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::JointMove >::value();
  }
  static const char* value(const ::wam_msgs::JointMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::JointMoveRequest> should match 
// service_traits::DataType< ::wam_msgs::JointMove > 
template<>
struct DataType< ::wam_msgs::JointMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::JointMove >::value();
  }
  static const char* value(const ::wam_msgs::JointMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_msgs::JointMoveResponse> should match 
// service_traits::MD5Sum< ::wam_msgs::JointMove > 
template<>
struct MD5Sum< ::wam_msgs::JointMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::JointMove >::value();
  }
  static const char* value(const ::wam_msgs::JointMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::JointMoveResponse> should match 
// service_traits::DataType< ::wam_msgs::JointMove > 
template<>
struct DataType< ::wam_msgs::JointMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::JointMove >::value();
  }
  static const char* value(const ::wam_msgs::JointMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_MSGS_MESSAGE_JOINTMOVE_H
