// Generated by gencpp from file wam_msgs/OrtnMove.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_ORTNMOVE_H
#define WAM_MSGS_MESSAGE_ORTNMOVE_H

#include <ros/service_traits.h>


#include <wam_msgs/OrtnMoveRequest.h>
#include <wam_msgs/OrtnMoveResponse.h>


namespace wam_msgs
{

struct OrtnMove
{

typedef OrtnMoveRequest Request;
typedef OrtnMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OrtnMove
} // namespace wam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_msgs::OrtnMove > {
  static const char* value()
  {
    return "86f723fe9a4be8979be87cd065276584";
  }

  static const char* value(const ::wam_msgs::OrtnMove&) { return value(); }
};

template<>
struct DataType< ::wam_msgs::OrtnMove > {
  static const char* value()
  {
    return "wam_msgs/OrtnMove";
  }

  static const char* value(const ::wam_msgs::OrtnMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_msgs::OrtnMoveRequest> should match 
// service_traits::MD5Sum< ::wam_msgs::OrtnMove > 
template<>
struct MD5Sum< ::wam_msgs::OrtnMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::OrtnMove >::value();
  }
  static const char* value(const ::wam_msgs::OrtnMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::OrtnMoveRequest> should match 
// service_traits::DataType< ::wam_msgs::OrtnMove > 
template<>
struct DataType< ::wam_msgs::OrtnMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::OrtnMove >::value();
  }
  static const char* value(const ::wam_msgs::OrtnMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_msgs::OrtnMoveResponse> should match 
// service_traits::MD5Sum< ::wam_msgs::OrtnMove > 
template<>
struct MD5Sum< ::wam_msgs::OrtnMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::OrtnMove >::value();
  }
  static const char* value(const ::wam_msgs::OrtnMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::OrtnMoveResponse> should match 
// service_traits::DataType< ::wam_msgs::OrtnMove > 
template<>
struct DataType< ::wam_msgs::OrtnMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::OrtnMove >::value();
  }
  static const char* value(const ::wam_msgs::OrtnMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_MSGS_MESSAGE_ORTNMOVE_H
