// Generated by gencpp from file wam_msgs/PoseMove.msg
// DO NOT EDIT!


#ifndef WAM_MSGS_MESSAGE_POSEMOVE_H
#define WAM_MSGS_MESSAGE_POSEMOVE_H

#include <ros/service_traits.h>


#include <wam_msgs/PoseMoveRequest.h>
#include <wam_msgs/PoseMoveResponse.h>


namespace wam_msgs
{

struct PoseMove
{

typedef PoseMoveRequest Request;
typedef PoseMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseMove
} // namespace wam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_msgs::PoseMove > {
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::wam_msgs::PoseMove&) { return value(); }
};

template<>
struct DataType< ::wam_msgs::PoseMove > {
  static const char* value()
  {
    return "wam_msgs/PoseMove";
  }

  static const char* value(const ::wam_msgs::PoseMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_msgs::PoseMoveRequest> should match 
// service_traits::MD5Sum< ::wam_msgs::PoseMove > 
template<>
struct MD5Sum< ::wam_msgs::PoseMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::PoseMove >::value();
  }
  static const char* value(const ::wam_msgs::PoseMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::PoseMoveRequest> should match 
// service_traits::DataType< ::wam_msgs::PoseMove > 
template<>
struct DataType< ::wam_msgs::PoseMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::PoseMove >::value();
  }
  static const char* value(const ::wam_msgs::PoseMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_msgs::PoseMoveResponse> should match 
// service_traits::MD5Sum< ::wam_msgs::PoseMove > 
template<>
struct MD5Sum< ::wam_msgs::PoseMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_msgs::PoseMove >::value();
  }
  static const char* value(const ::wam_msgs::PoseMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_msgs::PoseMoveResponse> should match 
// service_traits::DataType< ::wam_msgs::PoseMove > 
template<>
struct DataType< ::wam_msgs::PoseMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_msgs::PoseMove >::value();
  }
  static const char* value(const ::wam_msgs::PoseMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_MSGS_MESSAGE_POSEMOVE_H
