// Generated by gencpp from file tf_listen/tf_listen_mes.msg
// DO NOT EDIT!


#ifndef TF_LISTEN_MESSAGE_TF_LISTEN_MES_H
#define TF_LISTEN_MESSAGE_TF_LISTEN_MES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace tf_listen
{
template <class ContainerAllocator>
struct tf_listen_mes_
{
  typedef tf_listen_mes_<ContainerAllocator> Type;

  tf_listen_mes_()
    : position()
    , range(0.0)
    , frame()  {
      position.assign(0.0);
  }
  tf_listen_mes_(const ContainerAllocator& _alloc)
    : position()
    , range(0.0)
    , frame(_alloc)  {
  (void)_alloc;
      position.assign(0.0);
  }



   typedef boost::array<float, 3>  _position_type;
  _position_type position;

   typedef float _range_type;
  _range_type range;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _frame_type;
  _frame_type frame;




  typedef boost::shared_ptr< ::tf_listen::tf_listen_mes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tf_listen::tf_listen_mes_<ContainerAllocator> const> ConstPtr;

}; // struct tf_listen_mes_

typedef ::tf_listen::tf_listen_mes_<std::allocator<void> > tf_listen_mes;

typedef boost::shared_ptr< ::tf_listen::tf_listen_mes > tf_listen_mesPtr;
typedef boost::shared_ptr< ::tf_listen::tf_listen_mes const> tf_listen_mesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tf_listen::tf_listen_mes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tf_listen::tf_listen_mes_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tf_listen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tf_listen': ['/home/marcus/catkin_ws_WAM/src/tf_listen/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tf_listen::tf_listen_mes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_listen::tf_listen_mes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_listen::tf_listen_mes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_listen::tf_listen_mes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_listen::tf_listen_mes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_listen::tf_listen_mes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tf_listen::tf_listen_mes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a901d7f4fd98f5da78b1ed54da0312ac";
  }

  static const char* value(const ::tf_listen::tf_listen_mes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa901d7f4fd98f5daULL;
  static const uint64_t static_value2 = 0x78b1ed54da0312acULL;
};

template<class ContainerAllocator>
struct DataType< ::tf_listen::tf_listen_mes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tf_listen/tf_listen_mes";
  }

  static const char* value(const ::tf_listen::tf_listen_mes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tf_listen::tf_listen_mes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] position\n\
float32 range\n\
sensor_msgs/Image frame\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tf_listen::tf_listen_mes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tf_listen::tf_listen_mes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.range);
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tf_listen_mes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tf_listen::tf_listen_mes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tf_listen::tf_listen_mes_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    s << indent << "frame: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TF_LISTEN_MESSAGE_TF_LISTEN_MES_H
